# Generated by Django 2.1.3 on 2018-11-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('api_url', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_value', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('token_count', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('api_value', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('token_count', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
            ],
        ),
    ]
